### ISSUE TITLE
👥  Staff Bios

### ISSUE THREAD

**Issue by aridutilh** [PhotographyLounge/site#6]
- Aimbot: 
Polish nature photographer, born pentaxian. Server lurker. 

- DadC: 
Event photographer and ENG cameraman among other things. The server's fatherly figure. 

- Rey:
From London and doing Photography as a hobby. PL Moderator and part of the the Contest Management Team.

**Comment by MattA-Official** [comment]
@RealVagabond does Hyuno have a bio yet? The current list is now part of #5

**Comment by MattA-Official** [comment]
Closed due to no response.

**Comment by aridutilh** [comment]
> Closed due to no response.

Hyuno: Amateur photographer and analog lover based in Mexico. Moderating for only one Discord server. The sarcastic/quick-tempered mod.

Apologies for the late response! Just got it now :)
